export { HomePage } from './Home/Home'
export { AboutUsPage } from './AboutUs/AboutUs'
export { ContactUsPage } from './ContactUs/ContactUs'
export { NewsPage } from './News/News'
export { CarriersPage } from './Carriers/Carriers'
export { ShippersPage } from './Shippers/Shippers'
export { BrokersPage } from './Brokers/Brokers'
export { LogInPage } from './LogIn/LogIn'
